name: Scala

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Scala CI
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: sbt test
        env:
          GITHUB_TOKEN: ""
      - name: Format
        run: sbt scalafmtCheckAll scalafmtSbtCheck 'scalafixAll --check'
        env:
          GITHUB_TOKEN: ""
